// <auto-generated />
using ApiFiotec.Infraestruture.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiFiotec.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250512204921_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ApiFiotec.Models.Estado", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("NomeUf")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("tbl_estados");
                });

            modelBuilder.Entity("ApiFiotec.Models.Municipio", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<ushort>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("municipio");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("tbl_municipios");
                });

            modelBuilder.Entity("ApiFiotec.Models.Municipio", b =>
                {
                    b.HasOne("ApiFiotec.Models.Estado", "Estado")
                        .WithMany("Municipios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("ApiFiotec.Models.Estado", b =>
                {
                    b.Navigation("Municipios");
                });
#pragma warning restore 612, 618
        }
    }
}
