// <auto-generated />
using System;
using ApiFiotec.Infraestruture.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiFiotec.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250513134015_relatorios")]
    partial class relatorios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ApiFiotec.Models.Estado", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("NomeUf")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("tbl_estados");
                });

            modelBuilder.Entity("ApiFiotec.Models.Municipio", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<ushort>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("municipio");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("tbl_municipios");
                });

            modelBuilder.Entity("ApiFiotec.Models.Relatorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Arbovirose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("arbovirose");

                    b.Property<int>("CodigoIbge")
                        .HasColumnType("INTEGER")
                        .HasColumnName("codigo_ibge");

                    b.Property<string>("DadosRelatorio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dados_relatorio");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("municipio");

                    b.Property<int>("SemanaInicio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("semana_inicio");

                    b.Property<int>("SemanaTermino")
                        .HasColumnType("INTEGER")
                        .HasColumnName("semana_termino");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("tbl_relatorios");
                });

            modelBuilder.Entity("ApiFiotec.Models.Solicitante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("cpf");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Cpf" }, "idx_cpf")
                        .IsUnique();

                    b.ToTable("tbl_solicitantes");
                });

            modelBuilder.Entity("ApiFiotec.Models.Municipio", b =>
                {
                    b.HasOne("ApiFiotec.Models.Estado", "Estado")
                        .WithMany("Municipios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("ApiFiotec.Models.Relatorio", b =>
                {
                    b.HasOne("ApiFiotec.Models.Solicitante", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("ApiFiotec.Models.Estado", b =>
                {
                    b.Navigation("Municipios");
                });
#pragma warning restore 612, 618
        }
    }
}
